version: "3"
services: 
  app:
    restart: always
    build: .
    # command: bash -c "uvicorn myblog.asgi:application --host 0.0.0.0 --port 8000"
    command: bash -c "gunicorn myblog.asgi:application -w 4 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker"
    volumes:
      - .:/code
    ports: 
      - "8000:8000"
    depends_on: 
      - db
  db:
    image: mysql:5.7
    volumes: 
      - "./maysql:/var/lib/mysql"
    ports: 
      - "3306:3306"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myblog