version: "3"
services: 
  app:
    restart: always
    build: .
    # command: bash -c "uvicorn myblog.asgi:application --host 0.0.0.0 --port 8000"
    # command: bash -c "python3 manage.py migrate"
    command: bash -c "gunicorn myblog.asgi:application -w 4 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker"
    volumes:
      - .:/code
      - static-volume:/code/static
    expose:
      - "8000"
    # ports:
    #   - "8000:8000"
    depends_on: 
      - db
    networks: 
      - nginx_network
      - db_network

  db:
    image: mysql:5.7
    volumes: 
      - "./maysql:/var/lib/mysql"
    ports: 
      - "3306:3306"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myblog
    networks: 
      - db_network

  nginx:
    restart: always
    image: nginx:latest
    ports: 
      - "80:8080"
    volumes: 
      - static-volume:/code/static
      - ./config/nginx:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html
    depends_on: 
      - app
    networks: 
      - nginx_network

networks: 
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
volumes: 
  static-volume: